#Temps d'AFK avant d'être téléporter ou déconnecter, en minutes
time: 20
#Si cette valeur est true, le joueur sera kick du serveur, sinon le joueur sera téléporter au safe spawn du monde par défaut.
AFKKick: true
